spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test9?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 437406

# RSA 公钥和密钥文件路径
rsa:
  key:
    pubKeyPath: C:\Users\gaoshuang\Desktop\auth_key\id_key_rsa.pub
    priKeyPath: C:\Users\gaoshuang\Desktop\auth_key\id_key_rsa

# 显示执行的SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
